# Generated by Django 3.0 on 2019-12-16 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='enddate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='startdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
