# Generated by Django 3.0 on 2019-12-27 14:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('projects', '0002_auto_20191216_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignProjectDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('enddate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('completiontime', models.IntegerField()),
                ('status', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=1024)),
                ('assignemployeeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.EmployeeDetails')),
                ('assignprojectid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectDetails')),
            ],
        ),
    ]
