# Generated by Django 3.0 on 2019-12-27 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignproject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignprojectdetails',
            old_name='assignemployeeid',
            new_name='employeeid',
        ),
        migrations.RenameField(
            model_name='assignprojectdetails',
            old_name='assignprojectid',
            new_name='projectid',
        ),
        migrations.RenameField(
            model_name='assignprojectdetails',
            old_name='status',
            new_name='taskstatus',
        ),
    ]
