# Generated by Django 3.0 on 2019-12-18 11:40

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managername', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('contactno', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('emailid', models.EmailField(max_length=254)),
            ],
        ),
    ]
