# Generated by Django 3.0 on 2019-12-18 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('manager', '0002_auto_20191218_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeename', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('contactno', models.BigIntegerField()),
                ('emailid', models.EmailField(max_length=254)),
                ('skillsets', models.CharField(max_length=200)),
                ('managerid',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ManagerDetails')),
            ],
        ),
    ]
