# Generated by Django 3.0 on 2019-12-29 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20191218_1908'),
        ('employee', '0002_auto_20191228_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='managerid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managerid', to='manager.ManagerDetails'),
        ),
    ]
